In [3]:
print("hello world")

hello world


In [5]:
!pip install numpy


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 252.5 kB/s  0:00:207.3 kB/s eta 0:00:01

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip


In [12]:
#That was me getting started

In [6]:
import numpy as np

In [7]:
matrix = np.zeros((10,10))

In [8]:
for i in range(10):
    matrix[i,i]=1

In [9]:
print(matrix)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [13]:
#so now trying the HFT(high frequency trading) memory management stuff over here... it's gonna be crazy lol

In [15]:
massive_array =np.random.randn(10000,10000)

In [17]:
total_bytes = massive_array.nbytes
mb = total_bytes/(1024**2)

In [31]:
print(f"Size of array: {mb:.2f} MB")

Size of array: 762.94 MB


In [19]:
#btw, that 726mb that's the size you've just created !

In [20]:
#now, onto the Vectorized Speed !

In [22]:
%%timeit
result = massive_array *2

The slowest run took 8.38 times longer than the fastest. This could mean that an intermediate result is being cached.
57.4 ms ± 67.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [25]:
#what actually happenend above? NumPy uses "SIMD" (Single Instruction, Multiple Data) to talk directly to your Mac’s CPU
#which is why it's faster than standard python lists